// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUg-OvCybguutTRSzL2r_sNb_N8UaKsLM',
    appId: '1:192810103553:web:85d977fd4aa46dd4f7e100',
    messagingSenderId: '192810103553',
    projectId: 'flutter-firebase-palestra',
    authDomain: 'flutter-firebase-palestra.firebaseapp.com',
    storageBucket: 'flutter-firebase-palestra.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmI7B6s5bX92lKGPIe9DnGsWvcLNDJNSQ',
    appId: '1:192810103553:android:758b3f4fb15911f6f7e100',
    messagingSenderId: '192810103553',
    projectId: 'flutter-firebase-palestra',
    storageBucket: 'flutter-firebase-palestra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmmVNmVL2J4Op6btLZuos6d_lcJnOUdCc',
    appId: '1:192810103553:ios:4593c7ca783e831cf7e100',
    messagingSenderId: '192810103553',
    projectId: 'flutter-firebase-palestra',
    storageBucket: 'flutter-firebase-palestra.appspot.com',
    iosClientId: '192810103553-69590ur1b80v58fisfl6o1duf39ps64q.apps.googleusercontent.com',
    iosBundleId: 'lima.ricarth.flutterFirebasePalestra',
  );
}
